repo_url: https://github.com/unb-Sistemas-de-Machine-learning/scinewsAI-docs
repo_name: scinewsAI-docs

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - glightbox

site_name: scinewsAI-docs
nav:
  - Home: index.md
  - Arquitetura: architecture.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]